### ISSUE TITLE
Recommended build task for minimal slug size?

### ISSUE THREAD

**Issue by robinheghan** [upworthy/heroku-buildpack-boot#7]
If I understand how this works, every dependency that boot downloads is added to the heroku slug. So if my build task creates an uberjar, dependencies will be stored in both the uberjar and the slugs .m2 directory. Or have I got this wrong?

What would be the recommended build-task in regards to minimal slug size?

**Comment by paxan** [comment]
@Skinney this buildpack has been tailored to our main usecase: we use `boot` as Clojure scripting system, which necessitates having `.m2` as part of the slug.

I've created an experimental branch [exclude-m2](https://github.com/upworthy/heroku-buildpack-boot/compare/exclude-m2) which should allow you to prevent `.m2` from being copied into slug by setting `BOOTBUILD_EXCLUDE_M2=Yessss` (any non-empty string will do).

You can try this version of the buildpack out by appending `#exclude-m2` to your `BUILDPACK_URL` value.

Caveat: if at run time your app decides to invoke `boot`, it will spend eons bootstrapping itself from scratch since `~/.m2` would be missing on a dyno.

**Comment by robinheghan** [comment]
Cool. I won't have time to test this out until two weeks or so, but I'll let you know when I have.

Perhaps an alternative would be to only build a .jar (no uberjar) and add .m2 to the classpath? This way you would have the best of both worlds. Not sure how to do that as part of a buildpack though.

**Comment by paxan** [comment]
You could use `jar` built-in task.
Assuming you have `boot.build` in the root of your repo that specifies dependencies and other options, you can set `BOOTBUILD_CMD="boot jar"`

**Comment by robinheghan** [comment]
Sure, but how would you run that jar? is it just `java --jar target/sample.jar -classpath=~/.m2` ?

**Comment by paxan** [comment]
boot has classpath tasks, I haven't use them, but there should be
docs/examples elsewhere.
I envision you'd use "jar" task followed by "install" task and then one of
boot's classpath-aware tasks that let you execute code.

**Comment by robinheghan** [comment]
Cool beans. I still think .m2 exclusion will be better for my use case though. I'll let you know how it worked out once I've gotten around to test it :)
